// <auto-generated />
using System;
using EnsekTest.Integrations.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnsekTest.WebApi.Migrations
{
    [DbContext(typeof(MeterReadingContext))]
    [Migration("20210310205047_v001")]
    partial class v001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("EnsekTest.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("EnsekTest.MeterReading", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("MeterReadingDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("MeterReadValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId", "MeterReadingDateTime");

                    b.ToTable("MeterReadings");
                });

            modelBuilder.Entity("EnsekTest.MeterReading", b =>
                {
                    b.HasOne("EnsekTest.Account", "Account")
                        .WithMany("MeterReadings")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("EnsekTest.Account", b =>
                {
                    b.Navigation("MeterReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
